export type Industry = "dentist" | "salon" | "car";
export type SectionVariant = "luxury" | "basic" | "bold";
export type MockupStyle = "clean" | "basic" | SectionVariant;

export type MockupData = {
  businessName: string;
  industry: Industry;
  primaryColor: string;
  secondaryColor: string;
  accentColor?: string;
  backgroundColor?: string;
  textColor?: string;
  style: MockupStyle;
  services: string[];
  serviceDescriptions?: string[];
  servicesTitle?: string;
  galleryTitle?: string;
  testimonialsTitle?: string;
  contactTitle?: string;
  brandTone?: string;
  colorSuggestions?: string;
  layoutSuggestions?: string;
  logoText?: string;
  logoImage?: string;
  slogan?: string;
  heroHeadline?: string;
  heroDescription?: string;
  shortDescription?: string;
  aboutTitle?: string;
  aboutText?: string;
  mainCta?: string;
  secondaryCta?: string;
  specialOffer?: string;
  phone?: string;
  location?: string;
  workingHours?: string;
  audience?: string;
  heroImage?: string;
  galleryImages?: string[];
  serviceImages?: string[];
  teamImages?: string[];
  backgroundImages?: string[];
  reviews?: string[];
};
